version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - 6000:27017

  app:
    build: ./
    image: markov-bot
    environment:
      ENV_NAME: production
      DATABASE_URL: mongodb://mongo:27017/markov
    ports:
      - 3000:3000
